### ISSUE TITLE
Button disappears when after dismissing a modal view

### ISSUE THREAD

**Issue by pushchris** [manuelescrig/MEVFloatingButton#2]
I am using the button to trigger a UIImagePickerController to appear. After selecting or capturing an image, the modal is removed from the view, but the button has been as well. Simply setting `button.hidden = false` brings the button back, but it's annoying behavior to have to call that every time you return to the view controller containing the button.

Steps to replicate:
- Add button to tableView
- Present a UIImagePickerController
- Dismiss UIImagePickerController

**Comment by manuelescrig** [comment]
Thanks for the bug report.
I just fixed it and created a new release **version [1.1.2](https://github.com/manuelescrig/MEVFloatingButton/releases/tag/1.1.2)**.
