### ISSUE TITLE
Change size

### ISSUE THREAD

**Issue by sanidhya26** [manuelescrig/MEVFloatingButton#6]
How can I change the width and height of the button frame

**Comment by manuelescrig** [comment]
The only way to change the size of the button itself is using `button.imagePadding = 20.0f;`.
The button the way is build needs to have always the same height and width.

**Comment by riyanpratamap** [comment]
This button size depends on its image size. Can we resize it?

**Comment by manuelescrig** [comment]
As mentioned above:
> The only way to change the size of the button itself is using button.imagePadding = 20.0f;.
The button the way is build needs to have always the same height and width.

Hope it helps :-)

**Comment by riyanpratamap** [comment]
Thank you, @manuelescrig
