### ISSUE TITLE
Hide/remove button

### ISSUE THREAD

**Issue by giacgbj** [manuelescrig/MEVFloatingButton#7]
Is there a way to hide or remove the button?

**Comment by manuelescrig** [comment]
Setting `buttton.displayMode = MEVFloatingButtonDisplayModeNone` should make the trick.

**Comment by giacgbj** [comment]
It doesn't work.

The only workaround I created is to tag the button, let's say 42:

```
self.tableView.setFloatingButton(nil)
for view in self.tableView.subviews {
  if view.tag == 42 {
    view.removeFromSuperview()
  }
}

```
It would be nice to have that feature natively.
